apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ckstotebj-python 
  janus-idp.io/tekton: ckstotebj-python
  backstage.io/kubernetes-id: ckstotebj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ckstotebj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml